### PR TITLE
Avoid extra allocation in Encode

### PR DESCRIPTION
**Pull request by yznima**
(cherry picked from commit 857ce333bc789942d07d840dc509d8c07651f588)

### CODE REVIEW

**Comment by yznima** [comment]
@appian/datalayer-ha Could I get a review on this? This is the same commit as https://github.com/sv/kdbgo/pull/20

**Review by jkessler93 — APPROVED** [review]
LGTM, great job finding/fixing this!

**Review by nanhu18 — APPROVED** [review]
LGTM!

**Comment by yznima** [comment]
@jkessler93 Could you merge?

**Pull request merged**
