### PR TITLE
AN-110722: Fix Dates before 1707-09-22

### PR DESCRIPTION
**Pull request by yznima**
Date type is now encoded and decoded in a way that dates before 1707-09-23 work. The least tested time (required by ADS) is 1707-09-22.

Ticket: https://issues.appian.com/browse/AN-110722

### CODE REVIEW

**Comment by yznima** [comment]
@appian/datalayer-ha Could you review?

**Review by sbenderli — APPROVED** [review]
LGTM

**Comment by yznima** [comment]
@sbenderli Could you merge this?

**Comment by zubairsuri** [comment]
@yznima - please create a ticket for this and specify why we need this change.

**Comment by yznima** [comment]
@zubairsuri This PR a subtask of in https://github.com/appian/data-layer/pull/1248. I will use the same [ticket](https://issues.appian.com/browse/AN-110722) number for this

**Pull request merged**
